name: wiceq
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  flutter_easyloading:
  flutter_card_swiper: ^7.0.1
#  slider_button: ^2.1.0
  shared_preferences:
  connection_notifier: ^2.0.1
  carousel_slider: ^5.0.0
  provider: ^6.1.5+1
  cloud_firestore: ^6.1.0
  animated_splash_screen: ^1.3.0
  share_it: ^0.7.0
  card_swiper: ^3.0.1
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0




flutter:

  uses-material-design: true

  assets:
    - asset/img.jpg
    - asset/img2.jpg
    - asset/img3.jpg
    - asset/img4.jpg
    - asset/img6.jpg
    - asset/img7.jpg
    - asset/ps-card-image.jpeg
    - asset/bg-wallpepper.jpeg


  fonts:
    - family: PoetsenOne-Regular
      fonts:
        - asset: asset/font/PoetsenOne-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "asset/ps-card-image.jpeg"